### PR TITLE
Migrate solution example

### LINKED ISSUE #1: Migrate Solution example from MetalK8s repository
Move everything under `examples/metalk8s-solution-example` from https://github.com/scality/metalk8s to the root of this repository.

### LINKED ISSUE #2: Add pre-merge build of example-solution in the CI
Create an `eve/main.yml` file at the root of the repository to handle build of the Solution example in the CI.

### PR DESCRIPTION
**Pull request by alexandre-allard**
**Summary:**
* Import the metalk8s-example-solution from https://github.com/scality/metalk8s repository
* Remove the UI part
* Add pre-merge to build the Solution

Closes: #1
Closes: #2

### CODE REVIEW

**Review by gdemonet — DISMISSED** [review]
Could we get rid of the example UI somehow? It's really not up-to-date, we don't deploy it automatically, and it'll slow down CI builds a lot...

Otherwise, LGTM :)

**Comment by alexandre-allard** [comment]
@gdemonet UI part removed

**Review by TeddyAndrieux — APPROVED** [review]
Green build, so LGTM

**Pull request merged**
